version: "2"
services:
    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: neconetic
            MONGO_INITDB_ROOT_PASSWORD: neconetic
            MONGO_INITDB_DATABASE: neconetic
        volumes:
            - ./data:/data/db
        ports:
            - 27017:27017
             
