version: "2"
services:
    mongo:
        image: mongo
        command: [ "--replSet", "neconetic", "--bind_ip", "0.0.0.0"]
        environment:
            MONGO_INITDB_DATABASE: neconetic
            MONGO_REPLICA_SET_NAME: neconetic
        volumes:
            - ./data:/data/db
        ports:
            - 27017:27017
