version: "3.8"
services:
    mongo1:
        image: mongo:4.2
        command: ["--replSet", "neconetic", "--bind_ip", "localhost", "--port", "27017"]
        environment:
            MONGO_INITDB_DATABASE: neconetic
        volumes:
            # - ../scripts:/scripts
            - ./data/mongo-1:/data/db
        ports:
            - 27017:27017
    
