version: "2"
services:
    mongo:
        image: mongo
        command: [ "--replSet", "neconetic", "--bind_ip", "0.0.0.0"]
        environment:
            MONGO_INITDB_DATABASE: neconetic
            MONGO_REPLICA_SET_NAME: neconetic
        volumes:
            - ./data:/data/db
        ports:
            - 27017:27017
# rs.initiate(
#   {
#     _id : 'neconetic',
#     members: [
#       { _id : 0, host : "0.0.0.0:27017" },
#     ]
#   }
# )
# db.isMaster()