version: "2"
services:
    mongo:
        image: mongo
        environment:
            MONGO_INITDB_DATABASE: neconetic
        volumes:
            - econetic-db:/data/db
        ports:
            - 27017:27017

    data-service:
        build:
            context: ..
            dockerfile: docker/data-service/Dockerfile
        environment:
            STORAGE_URI: "mongodb://mongo:27017/?readPreference=primary&ssl=false"
        ports:
            - 8000:8000
        depends_on:
            - mongo

    dashboard-service:
        build:
            context: ..
            dockerfile: docker/dashboard-service/Dockerfile
        environment:
            DASHBOARD_SERVICE_HOST: "0.0.0.0"
            DASHBOARD_SERVICE_PORT: 8050
            DB_HOST: mongo
            DB_PORT: 27017
        ports:
            - 8050:8050
        depends_on:
            - mongo
            - data-service

    migrate-station:
        build:
            context: ..
            dockerfile: docker/migration/stations/Dockerfile
        environment:
            STORAGE_URI: "mongodb://mongo:27017/?readPreference=primary&ssl=false"
        depends_on:
            - mongo           

    migrate-eco-data:
        build:
            context: ..
            dockerfile: docker/migration/eco-data/Dockerfile
        environment:
            STORAGE_URI: "mongodb://mongo:27017/?readPreference=primary&ssl=false"
        depends_on:
            - mongo 
            - migrate-station

    migrate-profiler-wind:
        build:
            context: ..
            dockerfile: docker/migration/profiler/wind/Dockerfile
        environment:
            STORAGE_URI: "mongodb://mongo:27017/?readPreference=primary&ssl=false"
        depends_on:
            - mongo 
            - migrate-station

    migrate-profiler-temperature:
        build:
            context: ..
            dockerfile: docker/migration/profiler/temperature/Dockerfile
        environment:
            STORAGE_URI: "mongodb://mongo:27017/?readPreference=primary&ssl=false"
        depends_on:
            - mongo 
            - migrate-station
volumes:
    econetic-db: