version: "2"
services:
    mongo:
        image: mongo
        command: [ "--replSet", "neconetic", "--bind_ip", "127.0.0.1"]
        environment:
            MONGO_INITDB_DATABASE: neconetic
            MONGO_REPLICA_SET_NAME: neconetic
        volumes:
            - ./data:/data/db
        ports:
            - 27017:27017

    data-service:
        build:
            context: ..
            dockerfile: docker/data-service/Dockerfile
        environment:
            STORAGE_HOST: mongo
        ports:
            - 8000:8000
        depends_on:
            - mongo 