version: "3"
services:
    mongo:
        image: mongo
        container_name: mongo
        environment:
            MONGO_INITDB_DATABASE: neconetic
            MONGO_INITDB_ROOT_USERNAME: neconetic
            MONGO_INITDB_ROOT_PASSWORD: neconetic_secrete
        volumes:
            - econetic-db:/data/db
        ports:
            - 27017:27017

    data-service:
        build:
            context: ..
            dockerfile: docker/data-service/Dockerfile
        container_name: data-service
        environment:
            STORAGE_URI: "mongodb://neconetic:neconetic_secrete@mongo:27017/?readPreference=primary&ssl=false"
        ports:
            - 8000:8000
        depends_on:
            - mongo

    dashboard-service:
        build:
            context: ..
            dockerfile: docker/dashboard-service/Dockerfile
        container_name: dashboard-service
        environment:
            DASHBOARD_SERVICE_HOST: "0.0.0.0"
            DASHBOARD_SERVICE_PORT: 8050
            DB_HOST: mongo
            DB_PORT: 27017
        ports:
            - 8050:8050
        depends_on:
            - mongo
            - data-service

    migrate-station:
        build:
            context: ..
            dockerfile: docker/migration/stations/Dockerfile
        container_name: migrate-station
        environment:
            STORAGE_URI: "mongodb://neconetic:neconetic_secrete@mongo:27017/?readPreference=primary&ssl=false"
        depends_on:
            - mongo           

    migrate-eco-data:
        build:
            context: ..
            dockerfile: docker/migration/eco-data/Dockerfile
        container_name: migrate-eco-data
        environment:
            STORAGE_URI: "mongodb://neconetic:neconetic_secrete@mongo:27017/?readPreference=primary&ssl=false"
        depends_on:
            - mongo 
            - migrate-station

    # migrate-profiler-wind:
    #     build:
    #         context: ..
    #         dockerfile: docker/migration/profiler/wind/Dockerfile
    #     container_name: migrate-profiler-wind
    #     environment:
    #         STORAGE_URI: "mongodb://neconetic:neconetic_secrete@mongo:27017/?readPreference=primary&ssl=false"
    #     depends_on:
    #         - mongo 
    #         - migrate-station

    migrate-profiler-temperature:
        build:
            context: ..
            dockerfile: docker/migration/temperature/Dockerfile
        container_name: migrate-profiler-temperature
        environment:
            STORAGE_URI: "mongodb://neconetic:neconetic_secrete@mongo:27017/?readPreference=primary&ssl=false"
        depends_on:
            - mongo 
            - migrate-station
            
volumes:
    econetic-db:
